local emotelist = {
    { anim = "emoteXL_waving1" },
    { anim = "emoteXL_waving2" },
    { anim = "emoteXL_waving3" },
    { anim = "emoteXL_waving4" },
    { anim = "emoteXL_happycheer" },
    { anim = "emoteXL_sad" },
    { anim = "emoteXL_annoyed" },
    { anim = "research" },
    { anim = "emoteXL_loop_dance0", loop = true },
    { anim = "emote_loop_sit2", loop = true },
    { anim = "emote_loop_sit3", loop = true },
    { anim = "emote_loop_sit4", loop = true },
    { anim = "emoteXL_bonesaw" },
    { anim = "emoteXL_facepalm" },
    { anim = "emoteXL_kiss" },
    { anim = "emote_loop_toast", loop = true },
    { anim = "emote_flex" },
    { anim = "emote_impatient" },
    { anim = "emote_jumpcheer" },
    { anim = "emote_laugh" },
    { anim = "emote_shrug" },
    { anim = "emote_sleepy" },
    { anim = "emote_slowclap" },
    { anim = "emote_swoon" },
    { anim = "emoteXL_loop_dance6", loop = true },
    { anim = "emoteXL_loop_dance7", loop = true },
    { anim = "emoteXL_loop_dance8", loop = true },
    { anim = "emote_loop_carol", loop = true },
    { anim = "emote_yawn" },
    { anim = "emote_annoyed_palmdown" },
    { anim = "emote_sad" },
    { anim = "emote_angry" },
    { anim = "emote_strikepose" },
    { anim = "emote_feet" },
    { anim = "emote_hands" },
    { anim = "emote_hat" },
    { anim = "emote_pants" },
    { anim = "idle_tango_loop", loop = true },
    { anim = "look" },
    { anim = "idle_clack_loop", loop = true },
    { anim = "idle_tap_loop", loop = true },
    { anim = "idle_inaction", loop = true },
    { anim = "idle_hot_loop", loop = true },
    { anim = "idle_hot_pst" },
    { anim = "idle_groggy01_loop", loop = true },
    { anim = "gift_open_loop", loop = true },
    { anim = "gift_pre" },
    { anim = "giift_loop", loop = true },
    { anim = "refuseeat" },
    { anim = "spooked", loop = true },
    { anim = "idle_wardrobe1_loop", loop = true },
    { anim = "wendy_commune_pst" },
    { anim = "teleport" },
    { anim = "mime1" },
    { anim = "mime2" },
    { anim = "mime3" },
    { anim = "mime4" },
    { anim = "mime5" },
    { anim = "mime6" },
    { anim = "mime7" },
    { anim = "mime8" },
    { anim = "mime9" },
    { anim = "mime10" },
    { anim = "mime11" },
    { anim = "mime12" },
    { anim = "mime13" },
    { anim = "idle_walter" },
    { anim = "idle_winona" },
    { anim = "idle_wortox" },
    { anim = "idle_woodie" },
    { anim = "idle_wes" },
    { anim = "idle_wendy" },
    { anim = "idle_wormwood" },
    { anim = "idle_wurt" },
    { anim = "idle_wathgrithr" },
    { anim = "idle_warly" },
    { anim = "book" },
    { anim = "channel_loop", loop = true },
    { anim = "cointoss" },
    { anim = "flute" },
    { anim = "hide", loop = true },
    { anim = "horn" },
    { anim = "jump" },
    { anim = "multithrust" },
    { anim = "punch" },
    { anim = "parry_loop", loop = true },
    { anim = "pocketwatch_cast" },
    { anim = "powerup" },
    { anim = "shock", loop = true },
    { anim = "sing" },
    { anim = "sink" },
    { anim = "strum" },
    { anim = "upgrade" },
    { anim = "whistle" },
    { anim = "wortox_portal_jumpout", loop = true },
}

return emotelist
