local timerlist = {
    "cooldown_valkyriemode",
    "cooldown_shadowmode",
    "cooldown_thunderspell",
    "cooldown_freezingspell",
    "cooldown_shadowspell",
    "cooldown_shadowprison",
    "cooldown_manashield",
    "cooldown_princessblessing",
    "cooldown_rollingmagma",
    "cooldown_whitefrost",
    "cooldown_poisonspore",
    "cooldown_elfmelody",
    "cooldown_setsugetsuka",
    "cooldown_annihilation",
    "cooldown_desolatedive",
    "cooldown_voidphantom",
    "cooldown_phantomblossom",
    "stopelfmelody_full",
    "stopelfmelody_partial",
    "premelody",
    "chargingelement",
    "lightningrecharge",
    "entersneak",

    -- Not quite necessary
    "premagpiestep",
    "clearsetsugetsukacounter",
    "valkyriekeyonlongpress",
    "shadowkeyonlongpress",
    "shieldkeyonlongpress",
    "phantomslashready",
}

return timerlist
